### ISSUE TITLE
unused_arguments raises errors wrong

### ISSUE THREAD

**Issue by antpaw** [za-creature/coffeescope#20] opened 2016-06-15 14:23 UTC
I believe it's wrong to raise an error about unused arg if the first arg is unused, but the second one is used, you can't get to the second argument if you don't declare the first.

**Comment by za-creature** [comment] 2016-06-15 14:37
Duplicate of #11

**Closed as completed by za-creature** 2016-06-15 14:37 UTC
Labels: duplicate

**Comment by za-creature** [comment] 2016-06-15 14:39
Hey, thanks for the report. I will escalate this as now there's actual interest in the feature. I don't use coffeescript at this moment (not by choice), so I've been prioritizing other people's issues over my own.
